language: node_js
node_js:
  - 12.14.0
sudo: false
cache:
  directories:
    - node_modules
script:
  npm run test:coveralls
  npm run lint
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@2.12.0
    coveralls < ./coverage/lcov.info
